### ISSUE TITLE
Deployment using action fails

### ISSUE THREAD

**Issue by natalieorsi** [wastefull/db#1]
Using the action bitovi/github-actions-angular-to-github-pages@v1.0.0

Things to try:
1. Change output directory to only deploy the browser subfolder (Pages doesn't expect SSR output)
2. make sure angular.json isn't overriding --base-href in outputPath or baseHref
3. Add a 404 for SPA routing using a new build step:
  ```
      - name: Copy index.html to 404.html
      run: cp dist/app/browser/index.html dist/app/browser/404.html
  ```

Something along the lines of 
```
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - id: build-publish
        uses: bitovi/github-actions-angular-to-github-pages@v1.0.0
        with:
          path: dist/app/browser
      - name: Copy index.html to 404.html
        run: cp dist/app/browser/index.html dist/app/browser/404.html
```
